### PR TITLE
adding constraints

### PR DESCRIPTION
**Pull request by jefalon**
## Purpose
This PR adds the ability to add an arbitrary number of constraints based on the objective functions. Additionally, it fixes the bug with the minimum distance constraint when defining more than one type of controls. check the changes to params.rst for full details. 

## Type of change
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Comment by jefalon** [comment]
oh it also fixed another bug, where the min distance function was enforcing a separation of 2*HH not 2*RD

**Review by johnjasa — APPROVED** [review]
Good to go on my end! I haven't tried the parallel aspects yet, but it'd be nice to get this in and stress test it. I like the coverage increase.

@eyoung55, feel free to review or merge, I want to give you the chance for input before it's merged.

**Comment by jefalon** [comment]
I just tested it in parallel, but since the point blockage is not parallelized in this branch (that is in PR #63) it crashed. I'm testing again without using point blockage.

**Comment by jefalon** [comment]
ok running without the point blockage does work in parallel

**Review by eyoung55 — APPROVED** [review]
looking good! very excited to have such a comprehensive implementation where we can mix and match different problem definitions.

**Pull request merged**
