### PR TITLE
Fixed mpi optimizations 

### PR DESCRIPTION
**Pull request by jefalon**
This is to fix Issue #6

### CODE REVIEW

**Review by johnjasa — APPROVED** [review]
I approve all these changes! I do want the CI to pass, though, and it looks like at least one test is failing and maybe another is hanging. I just set the GH Actions to rerun again, so hopefully we get more definitive results soon.

**Comment by eyoung55** [comment]
I'm still not sure why this is the case, but sometimes `mpirun -n 2 pytest ...` produces an error, and the alternative we tested, `mpirun -n 2 python -m pytest ...`, seems to hang.  I can't reproduce it on my laptop, but it does seem to happen when running the CI.

Using the more straightforward `pytest parallel_reg.py` where `parallel_reg.py` invokes something like `mpirun -n 2 windse run ...` as a new process _does_ seem to work as expected and also tracks coverage, so even though it's maybe less clean, I think maybe we just leave it like this for now.

**Comment by johnjasa** [comment]
I'd agree with you that the latter solution is the best one. Thanks for digging into this, @eyoung55, this ended up being a doozy!

**Review by eyoung55 — APPROVED** [review]
I think it's in good shape after the latest testing finishes.  Hopefully this is a workable template for building out future parallel CI tests.  I'll post issues related to the errors encountered when running the other steady tests in parallel.

**Pull request merged**
