### PR TITLE
added alm log write statements in new helper function, raise optimization warning instead of ValueError

### PR DESCRIPTION
**Pull request by kilojoules**
I write statements from the depreciated update actuator line function. I think this resolves issue #30 https://github.com/NREL/WindSE/issues/30. I changed a ValueError to a warning, to allow monitoring of power without performing optimization. I think this partially resolves issue #31 https://github.com/NREL/WindSE/issues/31.

### CODE REVIEW

**Comment by johnjasa** [comment]
@eyoung55, it looks like the CI hanged and canceled here. Would you expect this behavior given what you recently found? Do we need to change something here or can we just rerun the CI and expect it to pass?

**Comment by eyoung55** [comment]
yeah, if i'm reading the log progress right, the place where it was hanging was a little weird, but i wouldn't be too surprised if it was the same underlying issue.  @kilojoules, can you merge in the latest changes from the dev branch so we can retest this (@johnjasa, am i saying that right?)?  Dev also now has some safer versions of the folder-creation steps that hold the output files, so it's probably a useful thing all around.

**Comment by johnjasa** [comment]
Nice, I've pushed those changes from dev to this PR

**Comment by eyoung55** [comment]
Looking good! Let's merge it!

**Pull request merged**
