### PR TITLE
Added the tag_output() command

### PR DESCRIPTION
**Pull request by jefalon**

### CODE REVIEW

**Comment by johnjasa** [comment]
I saw this failed on Travis, I think it's just caps in the path name, let's see if this tweak helps

**Comment by johnjasa** [comment]
All right, looks like the second test is passing but the first has differences compared to the truth values.
I don't have a good handle on if those are reasonable differences - what do you think, Jeff?

**Comment by johnjasa** [comment]
All right, looks like the second test is passing but the first has differences compared to the truth values.
I don't have a good handle on if those are reasonable differences - what do you think, Jeff?

**Comment by johnjasa** [comment]
All right, looks like the second test is passing but the first has differences compared to the truth values.
I don't have a good handle on if those are reasonable differences - what do you think, Jeff?

**Comment by jefalon** [comment]
@johnjasa Yeah that's probably close enough. That test uses mshr, which has the problem of generating different meshes on different architectures. That probably explains the larger error. 

Also, I love the new error formating! Good Edit!

**Comment by johnjasa** [comment]
Awesome! Good to merge on my end.

**Pull request merged**
